#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 07:21:55 2019

@author: usrdel
"""
import pandas as pd
import numpy as np
import os
import sqlite3

path_guardado = '/Users/usrdel/Documents/GitHub/py-eguez-sarzosa-vicente-adrian/03_Pandas/data/csv/artwork_data.pickle'

df_completo_pickle = pd.read_pickle(path_guardado)

df = df_completo_pickle.iloc[49980:50019,:].copy()


#  Tipos de archivos 
#  
#  - JSON
#  - SQL
#  - EXCEL


######################## Excel ##########################

df.to_excel('ejemplo_basico.xlsx')


























#